### ISSUE TITLE
Should consider Drupal module

### ISSUE THREAD

**Issue by smustgrave** [Lullabot/message_integration#1]
This is a great starting point for setting up a Message Stack! Would really recommend making it a Drupal module and maybe the community can help make it a universal starting point!.

**Comment by smustgrave** [comment]
And I'm willing to help too because this saved me so much time.  Honestly only changes I needed to do was

1. Update the content types.  This can probably be added to the form page.
2. Change the diff setting to use 'split_fields'.  Could probably pull the diff default settings and use those vs hardcoding.
3. Removed the custom libraries included.  Maybe we could add a default library to start with.

Know several projects that could benefits from this though

**Comment by smustgrave** [comment]
wondering if I have permission to turn this into a module on Drupal.org.

**Comment by deviantintegral** [comment]
@smustgrave glad to hear this is useful. Feel free to fork it over to a drupal.org project, and when you have an initial dev release out we can link to it in the README and mark this repo as archived.

**Comment by smustgrave** [comment]
Started the module https://www.drupal.org/project/message_integration

Still needs some work but getting there.
