### ISSUE TITLE
All users get comments regardless of flag

### ISSUE THREAD

**Issue by fallenturtle** [Lullabot/message_integration#2]
I suspect this is not an actual issue with the code, but an issue with me. I've been trying to use message_integration for sending notifications out to forum users. It's working great in regards to sending out emails to all users when a new thread(node) has been created, but for some reason when a user leaves a comment, all users also get a notification for that as well regardless if they have subscribed to that thread(node)'s comments.
I'm not very good at php, but can read it somewhat. I've been trying to figure out where the code is for checking if the users is subscribed or not to a node's comments. Is that in this module, or is that all in the message_subscribe contrib module?

Any help pointing me in the right direction would be greatly appreciated. Thank you for your time and this module.

**Comment by deviantintegral** [comment]
You may have better luck asking over at https://www.drupal.org/project/message_integration as another user is turning this into a proper Drupal module.
